#
###################################
# Site wide configuration
####################################
#
title: lyasee
email: lyasee@naver.com
description: A simple and awesome blog!
url: https://lyasee.github.io # the base hostname & protocol for your site
keywords: ["Programming", "NodeJS", "JAVA"]


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: lyasee
  avatar: profile.png
  job: "Developer"
  bio: "새로운 것을 좋아합니다."
  email: lyasee@naver.com
  disqus-shortname: lyasee
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lyasee #username
  gitlab: c335544 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: c335544@gmail.com #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: lyasee #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  telegram: #username
  reddit: #username


################
paginate: 5
paginate_path : "/page:num/"
gems:
  - jekyll-paginate